apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeOrder
  labels:
    app: cafeOrder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeOrder
  template:
    metadata:
      labels:
        app: cafeOrder
    spec:
      containers:
        - name: cafeOrder
          image: username/cafeOrder:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5