apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeProduct
  labels:
    app: cafeProduct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeProduct
  template:
    metadata:
      labels:
        app: cafeProduct
    spec:
      containers:
        - name: cafeProduct
          image: username/cafeProduct:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5