server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: cafeDelivery
          destination: cafe
          contentType: application/json
        event-out:
          destination: cafe
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8084

feign:
  client:
    url:
      productUrl: http://localhost:8081
      orderUrl: http://localhost:8082
      payUrl: http://localhost:8083
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: cafeDelivery
          destination: cafe
          contentType: application/json
        event-out:
          destination: cafe
          contentType: application/json
feign:
  client:
    url:
      productUrl: http://product:8080
      orderUrl: http://order:8080
      payUrl: http://pay:8080