apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeDelivery
  labels:
    app: cafeDelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeDelivery
  template:
    metadata:
      labels:
        app: cafeDelivery
    spec:
      containers:
        - name: cafeDelivery
          image: username/cafeDelivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5